name: "Tests"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
            
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan static analysis
        run: |
          if composer show | grep -q phpstan; then
            composer phpstan || vendor/bin/phpstan analyse
          else
            echo "PHPStan is not installed as a composer dependency. Skipping.";
          fi

      - name: Run php cs fixer
        run: composer cs-fix-validate
        
      - name: Run tests
        run: composer test-ci